function [f] = func_ver2_pen(x,m)

n = 0.75; %efficiency
p = 998; %density of water
g = 9.81;
h = 110; %head


Q = pi * x(2) * x(1)^2; %turbine flow


f = - (n * p * g * h * Q); %power generated by the turbine

f=f+m*max(x(1),0);
f=f+m*max(x(1)-3,0);
%f=f+m*max(6-x(2),0);
f=f+m*max(x(2)-20,0);
end

