function [f] = func_ver2(x)

n = 0.75; %efficiency
p = 998; %density of water
g = 9.81;
h = 110; %head

Q = pi * x(2) * x(1)^2; %turbine flow

Q_spill = pi * x(2) * x(3)^2; %spill flow

f(1) = - (n * p * g * h * Q); %power generated by the turbine

f(2) = Q_spill;


end



